#!/bin/bash

# Wireguard client setup script. Copy this to /usr/local/bin and invoke with peer
# public key and endpoint IP address

# build client endpoint config
[[ $UID -eq 0 ]] || sudo=sudo
$sudo sh -c 'umask 077; mkdir -p /etc/wireguard; cat > /etc/wireguard/wgclient.conf' <<_EOF
[Interface]
PrivateKey = CLIENT_PRIVATEKEY
Address = 10.0.10.2/24
DNS = 8.8.8.8, 8.8.4.4, 1.1.1.1, 1.0.0.1

[Peer]
PublicKey = $1
AllowedIPs = 10.0.10.1/24, 0.0.0.0/0
Endpoint = $2:51280
_EOF

# bring up client
[[ $UID -eq 0 ]] || sudo=sudo
$sudo sh -c 'wg-quick up wgclient'
